### create car 1
POST http://localhost:8081/car
Authorization: Bearer eyJhbGciOiJSUzI.
Content-Type: application/json

{
  "brand": "Hyundai",
  "model": "Tucson",
  "licensePlate": "2-CEW-082"
}

### create car 2
POST http://localhost:8081/car
Content-Type: application/json

{
"brand": "Tesla",
"model": "Model 3",
"licensePlate": "2-AHJ-485"
}

### create car 3
POST http://localhost:8081/car
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Model 3",
  "licensePlate": "2-KOP-789"
}

### create car 4
POST http://localhost:8081/car
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Model S",
  "licensePlate": "2-IOP-456"
}

### create car 5
POST http://localhost:8081/car
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Model S",
  "licensePlate": "2-OKL-756"
}

### create car 6
POST http://localhost:8081/car
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Model S",
  "licensePlate": "2-VHJ-478"
}

### create car 7
POST http://localhost:8081/car
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Model S",
  "licensePlate": "2-ACB-111"
}

### create car 8
POST http://localhost:8081/car
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Model S",
  "licensePlate": "2-AQW-111"
}

### create car 9
POST http://localhost:8081/car
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Model S",
  "licensePlate": "1-AAA-111"
}

### create car 10
POST http://localhost:8081/car
Content-Type: application/json

{
  "brand": "Mercerdes",
  "model": "EQE",
  "licensePlate": "2-BAA-111"
}

### create car 11
POST http://localhost:8081/car
Content-Type: application/json

{
  "brand": "Mercerdes",
  "model": "EQB",
  "licensePlate": "2-BBB-111"
}