apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-postgres
  template:
    metadata:
      labels:
        app: session-postgres
    spec:
      containers:
        - name: session-postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "SessionServiceAdmin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: session-postgres-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: session-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: session-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
