apiVersion: v1
kind: Service
metadata:
  name: maintenance-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    app: maintenance-service